### ISSUE TITLE
Don't worry about CLISP...

### ISSUE THREAD

**Issue by Hexstream** [szos/defconfig#17]
I thought I'd let you know that CLISP has not seen an *official* release in MORE THAN A DECADE, so it's probably fine if you don't support it. I certainly don't and won't, as I think it's grossly unfair to give the same consideration to CLISP as the actively officially maintained implementations like [SBCL](http://sbcl.org/).

**Comment by szos** [comment]
I realize that CLISP hasnt seen a release in a long time, but my view is that it is best to support as much as possible (within reason). While I've gotten defconfig working on CLISP (except for `with-atomic-setv*`, as that requires `:trivial-cltl2`) I have yet to get the test suite working, as `:fiveam` doesnt load on CLISP. I'm debating pushing the CLISP specific changes (just a bunch of `#-clisp` statements) and just removing the test system from CLISP. Given the trivial amount of work needed to get this system loading on CLISP, I think its worthwhile. And if anyone has issues on CLISP Ill address them as they come. I can always withdraw support.

**Comment by Hexstream** [comment]
Very well, feel free to make your own determinations about opportunity costs. :)

**Comment by szos** [comment]
If you encounter any other problems with defconfig, please do open more issues! :smiley:

**Comment by ams** [comment]
GNU CLISP is actively maintained (https://gitlab.com/gnu-clisp/clisp) -- that it has not seen a release in a while is not a reason to dismiss it.

**Comment by szos** [comment]
Thanks for the link! My searching hadnt brought up the gitlab repo. Ill clone it and see if fiveam loads (as opposed to my distros clisp package, whose age and origin are unknown to me at this time). As stated, id like to support as many implementations as possible, and aside from one macro everything in defconfig should be portable. Basic testing from the repl seems to work without problems in CLISP.

UPDATE: After cloning CLISP from the link you provided, it seems that not only does fiveam load without issue, but trivial-cltl2 does as well. More testing is needed, as the test suite fails to compile, but I think this bodes well. 

UPDATE: All problems regarding CLISP have been solved and all tests pass!


--
Free the programs
Free the people
Freedom from the
Mainframe's steeple

1. mar. 2021 09:31:34 Alfred M. Szmidt <notifications@github.com>:

**Comment by Hexstream** [comment]
> GNU CLISP is actively maintained

An *unofficial fork* of GNU CLISP is actively maintained, more specifically...

([Here is the official CLISP homepage](https://clisp.sourceforge.io/), for reference.)

> that it has not seen a release in a while is not a reason to dismiss it

Actually, from a basic usability and user-friendliness perspective, that it has not seen an official release in more than a decade is a pretty good reason to dismiss it, especially since there are multiple actively officially maintained modern alternatives, some with frequent releases.

I don't really mind if individual people still consciously decide to use CLISP and/or support it despite this, as long as it's not accidentally or deliberately misrepresented as some sort of perfectly viable alternative just as good as any other, when it's simply not the case.

**Comment by szos** [comment]
The gitlab repo is owned by the group gnu-clisp, and the two members/contributors are Bruno Haible and Sam S, who hold the copyright to clisp.

I think there isnt more to be said here that has any relevance to defconfig.


--
Free the programs
Free the people
Freedom from the
Mainframe's steeple

1. mar. 2021 12:52:17 Jean-Philippe Paradis <notifications@github.com>:
