### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [szos/defconfig#19]
Building with SBCL 2.1.10 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id 6ad34ba135ae8033984d0251617f98fe4426a14c

*defconfig* fails to build with the following error:

```
; caught WARNING:
;   * is not permitted as an argument to the FUNCTION type specifier
; 
; caught WARNING:
;   * is not permitted as an argument to the FUNCTION type specifier
...
; caught WARNING:
;   * is not permitted as an argument to the FUNCTION type specifier
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001C08103}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "defconfig" "classes">

```

*defconfig/tests* fails to build because of a failure in  _defconfig_.

[Full log here](http://report.quicklisp.org/2021-11-02/failure-report/defconfig.html)

**Comment by szos** [comment]
This should be resolved now. The offending function spec has been updated and a new release has been cut.
