### ISSUE TITLE
Implement atomic setv

### ISSUE THREAD

**Issue by szos** [szos/defconfig#3]
Taking inspiration from @sdilts implementation of `with-atomic-update`, I'm wondering if it isnt possible to implement that functionality without requiring a list of places to rollback. I think this could be possible by using `macrolet` to create a local `setv` macro, which collects places and their current values before calling `%setv`, and then wrapping everything else up in an error handler that will reset all these collected places to their collected values. However, I'm having trouble figuring out how to do this without using `eval` since we need to collect these places and their values at runtime. My current thinking is to collect the quoted place name and the place value, and then reset them if an error is encountered. 

Development of this should occur in the `atomic-setv` branch. 

I think we might need a compiler macro to do this, as we need to code walk before macro expansion time in order to do this (i think... im very unsure - ive never written a compiler macro before). 

The expansion that would be optimal is as follows: 
```
(with-atomic-setv
  (let ((x 1)
	(sym (gensym)))
    (setv *x* x
	  *sym* sym)
    (print 'hi)
    (setv *x* "string"
	  *sym* "string")))
```
should expand into: 
```
(let ((#:*x*123 *x*)
      (#:*sym*123 *sym*))
  (handler-case
      (let ((x 1)
	    (sym (gensym)))
	(setv *x* x
	      *sym* sym)
	(print 'hi)
	(setv *x* "string"
	      *sym* "string"))
    (invalid-datum-error (c)
      (setf *x* #:*x*123
	    *sym* #:*sym*123))))
```

**Comment by sdilts** [comment]
IIRC, compiler macros are the last thing to be expanded, and are generally supposed to be used to transform code into equivalent but more efficient code, so they wouldn't really be a good idea here. The `sb-cltl2` package shipped with SBCL has some functions like `macroexpand-all` that provide code analysis functions. The `trivial-cltl2` package from QuickLisp provides the same functionality, except it will work with most CL implementations instead of just SBCL.

**Comment by szos** [comment]
Thanks for the tip on `trivial-cltl2`, as well as the info on compiler macros! I had assumed they ran at compile time instead of macroexpasion time. I'm trying to figure a way to do this without needing to write a code walker. ill try more with macrolet.

EDIT: i think this can be solved with macrolet and compiler-let, by pushing all the places into a compiler-let dynamic variable, and then generating handler-case's for every setv individually instead of trying to communicate it back to with-atomic-setv.

**Comment by szos** [comment]
`with-atomic-setv` has been implemented using compiler-let and macrolet. While it expands into far more `handler-case` statements than id like, it gets the job done.
